import http from 'k6/http';
import { check, group } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';

// Load test configuration generated by setup script
let config;
try {
  config = JSON.parse(open('./test-config.json'));
} catch (e) {
  config = {
    apiBaseUrl: 'http://host.docker.internal:3000',
    primaryShortCode: 'eWCPdV',
    shortCodes: ['eWCPdV'],
  };
}

// Custom metrics for status codes
const status200 = new Counter('status_200');
const status302 = new Counter('status_302');
const status404 = new Counter('status_404');
const status5xx = new Counter('status_5xx');
const redirectLatency = new Trend('redirect_latency_ms');

export const options = {
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
  scenarios: {
    redirect_load: {
      executor: 'ramping-vus',
      startVUs: 5,
      stages: [
        { duration: '5s', target: 20 },
        { duration: '15s', target: 50 },
        { duration: '10s', target: 100 },
        { duration: '5s', target: 0 },
      ],
      gracefulRampDown: '5s',
    },
  },
};



export default function () {
  // Select short code randomly from configured list or primary
  const codes = config.shortCodes && config.shortCodes.length > 0 ? config.shortCodes : [config.primaryShortCode];
  const shortCode = codes[Math.floor(Math.random() * codes.length)];
  const baseUrl = config.apiBaseUrl.replace('localhost', 'host.docker.internal').replace('127.0.0.1', 'host.docker.internal');

  // Disable automatic redirect following so we measure the 302 backend execution time
  const params = {
    redirects: 0,
    tags: { name: 'RedirectEndpoint' },
  };

  const res = http.get(`${baseUrl}/s/${shortCode}`, params);

  // Track latency
  redirectLatency.add(res.timings.duration);

  // Track status codes
  if (res.status === 302) {
    status302.add(1);
  } else if (res.status === 200) {
    status200.add(1);
  } else if (res.status === 404) {
    status404.add(1);
  } else if (res.status >= 500) {
    status5xx.add(1);
  }

  // Verification checks
  check(res, {
    'is status 302': (r) => r.status === 302,
    'has location header': (r) => r.headers['Location'] !== undefined,
  });
}
